export const TRANSACTION_LIST_TABLE_SETTING_DATA = [
    {
        name: 'Hesab',
        dataIndex: 'cashboxName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'İcra tarixi',
        dataIndex: 'createdAt',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Əməliyyat tarixi',
        dataIndex: 'dateOfTransaction',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Sənəd',
        dataIndex: 'documentNumber',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Növ',
        dataIndex: 'operationDirectionId',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Kateqoriya',
        dataIndex: 'categoryName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Alt kateqoriya',
        dataIndex: 'subCategoryName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qarşı tərəf',
        dataIndex: 'contactOrEmployee',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Məbləğ',
        dataIndex: 'amount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Əsas valyuta',
        dataIndex: 'amountConvertedToMainCurrency',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Biznes blok',
        dataIndex: 'businessUnitId',
        standart: true,
        visible: true,
        fixed: false,
    },

    {
        name: 'Status',
        dataIndex: 'status',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Məsul şəxs',
        dataIndex: 'createdByName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Ödəniş növü',
        dataIndex: 'paymentTypeName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə məlumat',
        dataIndex: 'description',
        standart: false,
        visible: false,
        fixed: false,
    },
];
export const RECEIVABLES_TABLE_SETTING_DATA = [
    {
        name: 'Qarşı tərəf',
        dataIndex: 'contactFullName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Toplam Borclar',
        dataIndex: 'invoiceDebtAmount',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Ödənilib',
        dataIndex: 'convertedPaidAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilib(%)',
        dataIndex: 'paidInPercentage',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilməlidir',
        dataIndex: 'amountToBePaid',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş',
        dataIndex: 'lastPaymentAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş tarixi',
        dataIndex: 'dateOfTransaction',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Günlərin sayı',
        dataIndex: 'daysNum',
        standart: true,
        visible: true,
        fixed: false,
    },
];
export const PAYABLES_TABLE_SETTING_DATA = [
    {
        name: 'Qarşı tərəf',
        dataIndex: 'contactFullName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Toplam Borclar',
        dataIndex: 'invoiceDebtAmount',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Ödənilib',
        dataIndex: 'convertedPaidAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilib(%)',
        dataIndex: 'paidInPercentage',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilməlidir',
        dataIndex: 'amountToBePaid',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş',
        dataIndex: 'lastPaymentAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş tarixi',
        dataIndex: 'dateOfTransaction',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Günlərin sayı',
        dataIndex: 'daysNum',
        standart: true,
        visible: true,
        fixed: false,
    },
];

export const VAT_TABLE_SETTING_DATA = [
    {
        name: 'Qarşı tərəf',
        dataIndex: 'contactFullName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Toplam Borc',
        dataIndex: 'invoiceDebtAmount',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Ödənilib',
        dataIndex: 'convertedPaidAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilib(%)',
        dataIndex: 'paidAmountPercentage',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilməlidir',
        dataIndex: 'amountToBePaid',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş',
        dataIndex: 'lastPaymentAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş tarixi',
        dataIndex: 'dateOfTransaction',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Günlərin sayı',
        dataIndex: 'daysNum',
        standart: true,
        visible: true,
        fixed: false,
    },
];

export const ADVANCE_REPORTS_TABLE_SETTING_DATA = [
    {
        name: 'Qarşı tərəf',
        dataIndex: 'contactFullName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Məxaric',
        dataIndex: 'amountCashOut',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Mədaxil',
        dataIndex: 'amountCashIn',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Balans',
        dataIndex: 'balance',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş',
        dataIndex: 'lastTransactionAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş tarixi',
        dataIndex: 'lastTransactionDate',
        standart: true,
        visible: true,
        fixed: false,
    },
];

export const EMPLOYEE_REPORTS_TABLE_SETTING_DATA = [
    {
        name: 'Əməkdaş',
        dataIndex: 'employeeName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Məxaric',
        dataIndex: 'amountCashOut',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Mədaxil',
        dataIndex: 'amountCashIn',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Balans',
        dataIndex: 'balance',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş',
        dataIndex: 'lastTransactionAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş tarixi',
        dataIndex: 'lastTransactionDate',
        standart: true,
        visible: true,
        fixed: false,
    },
];

export const BALANCE_REPORTS_TABLE_SETTING_DATA = [
    {
        name: 'Təsisçi',
        dataIndex: 'tenantPersonName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Məxaric',
        dataIndex: 'amountCashOut',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Mədaxil',
        dataIndex: 'amountCashIn',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Balans',
        dataIndex: 'balance',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş',
        dataIndex: 'lastTransactionAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son ödəniş tarixi',
        dataIndex: 'lastTransactionDate',
        standart: true,
        visible: true,
        fixed: false,
    },
];

export const CURRENCIES_REPORTS_TABLE_SETTING_DATA = [
    {
        name: 'Başlama tarixi',
        dataIndex: 'startAt',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Bitmə tarixi',
        dataIndex: 'endAt',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Valyuta',
        dataIndex: 'currencyCode',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Son məzənnə',
        dataIndex: 'rate',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Əvvəlki məzənnə',
        dataIndex: 'prevRate',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Dinamika (%)',
        dataIndex: 'dynamicsPercent',
        standart: true,
        visible: true,
        fixed: false,
    },
];

export const PAYMENTTABLE_CREDITTABLE_TABLE_SETTING_DATA = [
    {
        name: 'İcra tarixi',
        dataIndex: 'createdAt',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qarşı tərəf',
        dataIndex: 'contactName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Sənəd',
        dataIndex: 'serialNumber',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Kredit növü',
        dataIndex: 'creditTypeName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Kredit məbləği',
        dataIndex: 'totalInvoiceAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilib',
        dataIndex: 'totalPaidAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilib(%)',
        dataIndex: 'totalPaidAmountPercentage',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənilməlidir',
        dataIndex: 'remainingAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Aylıq ödəniş',
        dataIndex: 'monthlyPaymentAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Müddət (Ay)/dəfə',
        dataIndex: 'numberOfMonths',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qaimə',
        dataIndex: 'invoiceNumber',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Status',
        dataIndex: 'status',
        standart: true,
        visible: true,
        fixed: false,
    }
];

export const PAYMENTTABLE_CREDITPAYMT_TABLE_SETTING_DATA = [
    {
        name: 'Qarşı tərəf',
        dataIndex: 'contactName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Sənəd',
        dataIndex: 'serialNumber',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Kredit məbləği',
        dataIndex: 'totalInvoiceAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Sənəd üzrə qalıq',
        dataIndex: 'remainingAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödəniş məbləği',
        dataIndex: 'monthlyPaymentAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödəniş tarixi',
        dataIndex: 'date',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Status',
        dataIndex: 'status',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qaimə',
        dataIndex: 'invoiceNumber',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Gecikmə (gün)',
        dataIndex: 'latenessDays',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ödənişlərin sayı',
        dataIndex: 'numberOfMonths',
        standart: true,
        visible: true,
        fixed: false,
    }
];
