export const HRM_REPORTS_SALARY_TABLE_SETTING_DATA = [
    {
        name: 'Əməkdaş',
        dataIndex: 'name',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Valyuta',
        dataIndex: 'currencyCode',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Aylıq maaş',
        dataIndex: 'salary',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Maaşa əlavə',
        dataIndex: 'salaryAddition',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Tutulmalar',
        dataIndex: 'salaryDeduction',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Gecikmələr',
        dataIndex: 'latenessPenalty',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Satışdan bonus',
        dataIndex: 'salesBonusAmount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Bu ay cəmi',
        dataIndex: 'totalSalary',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ötən dövrlərdən qalıq',
        dataIndex: 'previousBalance',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Bu ay ödənilmiş',
        dataIndex: 'salaryPayment',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Cari qalıq',
        dataIndex: 'currentBalance',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Status',
        dataIndex: 'isArchived',
        standart: true,
        visible: true,
        fixed: true,
    },
];
