export const CONTACTS_TABLE_SETTING_DATA = [
    {
        name: 'Əlaqə tipi',
        dataIndex: 'type',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Kateqoriya',
        dataIndex: 'categoryIds',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Ad',
        dataIndex: 'name',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Əlaqə tel',
        dataIndex: 'phoneNumbers',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Email',
        dataIndex: 'emails',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Status',
        dataIndex: 'status',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Menecer',
        dataIndex: 'manager',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'VÖEN',
        dataIndex: 'voen',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Websayt',
        dataIndex: 'websites',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Ünvan',
        dataIndex: 'address',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Qiymət tipi',
        dataIndex: 'priceType',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə məlumat',
        dataIndex: 'description',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əməliyyat tarixi',
        dataIndex: 'createdAt',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə olunub',
        dataIndex: 'createdBy',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Şirkət adı',
        dataIndex: 'officialName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Baş direktor',
        dataIndex: 'generalDirector',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'VÖEN (Şirkət)',
        dataIndex: 'companyVoen',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Bank adı',
        dataIndex: 'bankName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'VÖEN (Bank)',
        dataIndex: 'bankVoen',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Kod',
        dataIndex: 'bankCode',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Müxbir hesab (M/h)',
        dataIndex: 'correspondentAccount',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Hesablaşma hesabı (H/h)',
        dataIndex: 'settlementAccount',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'S.W.I.F.T.',
        dataIndex: 'swift',
        standart: false,
        visible: false,
        fixed: false,
    },
];
export const PARTNERS_TABLE_SETTING_DATA = [
    {
        name: 'Partnyor',
        dataIndex: 'name',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Email',
        dataIndex: 'email',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Mobil telefon',
        dataIndex: 'phoneNumbers',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Kateqoriya',
        dataIndex: 'categoryIds',
        standart: true,
        visible: true,
        fixed: false,
    },

    {
        name: 'Qiymət tipi',
        dataIndex: 'priceTypeId',
        standart: true,
        visible: true,
        fixed: false,
    },

    {
        name: 'Əlaqə statusu',
        dataIndex: 'status',
        standart: true,
        visible: true,
        fixed: false,
    },

    // {
    //     name: 'VÖEN',
    //     dataIndex: 'voen',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Websayt',
    //     dataIndex: 'websites',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Ünvan',
    //     dataIndex: 'address',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Çatdırılma ünvanı',
    //     dataIndex: 'deliveryAddress',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Menecer',
    //     dataIndex: 'manager',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Əlavə məlumat',
    //     dataIndex: 'description',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Əməliyyat tarixi',
    //     dataIndex: 'createdAt',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Əlavə olunub',
    //     dataIndex: 'createdBy',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Şirkət adı',
    //     dataIndex: 'officialName',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Baş direktor',
    //     dataIndex: 'generalDirector',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'VÖEN (Şirkət)',
    //     dataIndex: 'companyVoen',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Bank adı',
    //     dataIndex: 'bankName',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'VÖEN (Bank)',
    //     dataIndex: 'bankVoen',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Kod',
    //     dataIndex: 'bankCode',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Müxbir hesab (M/h)',
    //     dataIndex: 'correspondentAccount',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'Hesablaşma hesabı (H/h)',
    //     dataIndex: 'settlementAccount',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
    // {
    //     name: 'S.W.I.F.T.',
    //     dataIndex: 'swift',
    //     standart: false,
    //     visible: false,
    //     fixed: false,
    // },
];
