export const Sales_Invoices_TABLE_SETTING_DATA = [
    {
        name: 'Əməliyyat növü',
        dataIndex: 'invoiceType',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'İcra tarixi',
        dataIndex: 'createdAt',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Əməliyyat tarixi',
        dataIndex: 'operationDate',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qarşı tərəf',
        dataIndex: 'counterparty',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Müqavilə',
        dataIndex: 'contractNo',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qaimə',
        dataIndex: 'invoiceNumber',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Ödəniş statusu',
        dataIndex: 'paymentStatus',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son qiymət',
        dataIndex: 'endPrice',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son qiymət (Əsas valyuta)',
        dataIndex: 'endPriceInMainCurrency',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Biznes blok',
        dataIndex: 'businessUnitId',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Satış meneceri',
        dataIndex: 'salesmanName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Status',
        dataIndex: 'statusOfOperationLabel',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Məbləğ',
        dataIndex: 'amount',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə olunub',
        dataIndex: 'operatorName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Anbar',
        dataIndex: 'stockName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Ödənilməlidir',
        dataIndex: 'endPriceCache',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Endirim (%)',
        dataIndex: 'discountPercentage',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Endirim',
        dataIndex: 'discountAmount',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Məhsul miqdarı',
        dataIndex: 'totalQuantity',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Vergi (%)',
        dataIndex: 'taxPercentage',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Vergi',
        dataIndex: 'taxAmount',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Agent',
        dataIndex: 'agentName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə məlumat',
        dataIndex: 'description',
        standart: false,
        visible: false,
        fixed: false,
    },
];

export const Sales_SoldItems_TABLE_SETTING_DATA = [
    {
        name: 'Anbar',
        dataIndex: 'warehouseName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Kataloq',
        dataIndex: 'rootCatalogName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Alt kataloq',
        dataIndex: 'catalogName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Məhsul',
        dataIndex: 'productName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Say',
        dataIndex: 'quantity',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Ölçü vahidi',
        dataIndex: 'unitOfmeasuring',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Vahidin qiyməti',
        dataIndex: 'pricePerUnitInMainCurrency',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Toplam qiymət',
        dataIndex: 'totalPriceInMainCurrency',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Endirim',
        dataIndex: 'discountAmountPerUnit',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Endirim(%)',
        dataIndex: 'discountAmountPerUnitPercentage',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son qiymət',
        dataIndex: 'endPricePerUnitInMainCurrency',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Vahidin son qiyməti',
        dataIndex: 'endPricePerUnitInMainCurrencyUnit',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Vahidin maya dəyəri',
        dataIndex: 'costPerUnitInMainCurrency',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Maya dəyəri',
        dataIndex: 'costOfGoodsSoldInMainCurrency',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Mənfəət',
        dataIndex: 'endPricePerUnitInMainCurrencyProfit',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Marja',
        dataIndex: 'endPricePerUnitInMainCurrencyMargin',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Tarix',
        dataIndex: 'operationDate',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Müqavilə',
        dataIndex: 'contractNumber',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qaimə',
        dataIndex: 'invoiceNumber',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Alıcı',
        dataIndex: 'clientName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Satış meneceri',
        dataIndex: 'salesman',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Agent',
        dataIndex: 'agent',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Əməliyyatçı',
        dataIndex: 'operator',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Məhsul tipi',
        dataIndex: 'isServiceType',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Seriya nömrəsi',
        dataIndex: 'isWithoutSerialNumber',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Barkod',
        dataIndex: 'barcode',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Şəkil',
        dataIndex: 'attachmentName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'İstehsalçı',
        dataIndex: 'manufacturerName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Məhsul kodu',
        dataIndex: 'productCode',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Satış qiyməti',
        dataIndex: 'pricePerUnit',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə məlumat',
        dataIndex: 'description',
        standart: false,
        visible: false,
        fixed: false,
    },
];

export const Sales_Purchased_TABLE_SETTING_DATA = [
    {
        name: 'Anbar',
        dataIndex: 'warehouseName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Kataloq',
        dataIndex: 'rootCatalogName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Alt kataloq',
        dataIndex: 'catalogName',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Məhsul adı',
        dataIndex: 'productName',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Say',
        dataIndex: 'quantity',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Ölçü vahidi',
        dataIndex: 'unitOfmeasuring',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Vahidin qiyməti',
        dataIndex: 'costPerUnit',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Toplam qiymət',
        dataIndex: 'totalCost',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Endirim (%)',
        dataIndex: 'discountAmountPerUnit',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Son qiymət',
        dataIndex: 'endPricePerUnit',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Vahidin son qiyməti',
        dataIndex: 'endPricePerUnitInMainCurrencyUnit',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Əsas valyuta',
        dataIndex: 'endPriceInMainCurrency',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Tarix',
        dataIndex: 'operationDate',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Müqavilə',
        dataIndex: 'contractNumber',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qaimə',
        dataIndex: 'invoiceNumber',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Təchizatçı',
        dataIndex: 'supplier',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Agent',
        dataIndex: 'agent',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Əməliyyatçı',
        dataIndex: 'operator',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Məhsul tipi',
        dataIndex: 'isServiceType',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Seriya nömrəsi',
        dataIndex: 'isWithoutSerialNumber',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Barkod',
        dataIndex: 'barcode',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Şəkil',
        dataIndex: 'attachmentName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'İstehsalçı',
        dataIndex: 'manufacturerName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Məhsul kodu',
        dataIndex: 'productCode',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Satış qiyməti',
        dataIndex: 'pricePerUnit',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə məlumat',
        dataIndex: 'description',
        standart: false,
        visible: false,
        fixed: false,
    },
];
export const Sales_GoodTurnovers_TABLE_SETTING_DATA = [
    {
        name: 'Anbar',
        dataIndex: 'stock_name',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Kateqoriya',
        dataIndex: 'catalog_name',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Alt kateqoriya',
        dataIndex: 'subcatalog_name',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Məhsul',
        dataIndex: 'product_name',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Ölçü vahidi',
        dataIndex: 'unit_of_measurement_name',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Dövrün əvvəlinə',
        dataIndex: 'start_of_period',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Daxil olma',
        dataIndex: 'income',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Xaric olma',
        dataIndex: 'outgo',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Dövrün sonuna',
        dataIndex: 'endOfPeriod',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Məhsul tipi',
        dataIndex: 'isServiceType',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Seriya nömrəsi',
        dataIndex: 'isWithoutSerialNumber',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Barkod',
        dataIndex: 'barcode',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Şəkil',
        dataIndex: 'attachmentName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'İstehsalçı',
        dataIndex: 'manufacturerName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Məhsul kodu',
        dataIndex: 'productCode',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Satış qiyməti',
        dataIndex: 'pricePerUnit',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə məlumat',
        dataIndex: 'description',
        standart: false,
        visible: false,
        fixed: false,
    },
];

export const Sales_Contracts_TABLE_SETTING_DATA = [
    {
        name: 'Qarşı tərəf',
        dataIndex: 'counterparty_name',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Müqavilə',
        dataIndex: 'contract_no',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Məsul şəxs',
        dataIndex: 'responsible_person_name',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Başlama tarixi',
        dataIndex: 'start_date',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Bitmə tarixi',
        dataIndex: 'end_date',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Günlərin sayı',
        dataIndex: 'days_to_end',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Məbləğ',
        dataIndex: 'amount',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Dövriyyə',
        dataIndex: 'turnover',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Qalıq',
        dataIndex: 'rest',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Status',
        dataIndex: 'status',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Valyuta',
        dataIndex: 'currencycode',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Növ',
        dataIndex: 'contract_type',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'İstiqamət',
        dataIndex: 'direction',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlaqəli tərəflər',
        dataIndex: 'related_contacts',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə məlumat',
        dataIndex: 'description',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Biznes blok',
        dataIndex: 'business_unit_id',
        standart: false,
        visible: false,
        fixed: false,
    },
];

export const Sales_Production_TABLE_SETTING_DATA = [
    {
        name: 'İcra tarixi',
        dataIndex: 'createdAt',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Sifarişçi',
        dataIndex: 'clientId',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Sənəd',
        dataIndex: 'invoiceNumber',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Planlaşdırılmış maya dəyəri',
        dataIndex: 'planned_cost',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Faktiki maya dəyəri',
        dataIndex: 'cost',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Yayınma',
        dataIndex: 'planned_cost_deviation',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Yayınma %',
        dataIndex: 'planned_cost_percentage',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Məhsul miqdarı',
        dataIndex: 'totalQuantity',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Biznes blok',
        dataIndex: 'businessUnitId',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Müddət/Cari müddət (gün)',
        dataIndex: 'CurrentDate',
        standart: true,
        visible: true,
        fixed: false,
    },
    {
        name: 'Status',
        dataIndex: 'status',
        standart: true,
        visible: true,
        fixed: true,
    },
    {
        name: 'Başlama tarixi',
        dataIndex: 'startDate',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Bitmə tarixi',
        dataIndex: 'endDate',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Gecikmə, gün',
        dataIndex: 'daysPassed',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Menecer',
        dataIndex: 'salesmanName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Müqavilə',
        dataIndex: 'contractNo',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Materiallar anbarı',
        dataIndex: 'productionMaterialsStockName',
        standart: false,
        visible: false,
        fixed: false,
    },
    {
        name: 'Əlavə məlumat',
        dataIndex: 'description',
        standart: false,
        visible: false,
        fixed: false,
    },
];
